### ISSUE TITLE
[Question] Where is the install alias that's being used? I couldn't find it.

### ISSUE THREAD

**Issue by shubhamkumar13** [zshipko/ocaml-vec#1]
I was going through the installation instruction and it works perfectly, just that I can't seem to find the install stanza or install alias.
I'm not sure if I'm missing something

**Comment by zshipko** [comment]
There isn’t an install stanza in the dune file, I believe the `public_name` field is all that’s needed to get the package to be installed correctly: https://github.com/zshipko/ocaml-vec/blob/master/src/dune#L15

**Comment by shubhamkumar13** [comment]
Thanks for clearing that up!
